#https://app.apiary.io/trentose2jan12m178127/editor
swagger: "2.0"
info:
  version: 1.0.0
  title: "trentose2jan12m178127"
  description: API per gli astronauti
  contact:
    name: Stefano Leonardi
    email: stefano.leonardi-2@studenti.unitn.it
host: trentose2jan12-m178127.herokuapp.com
basePath: /astronauts/
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
            
  /:       
    get:
      description: prende tutti gli astronauti
      operationId: getAllAstronauts
      parameters:
        - name: lastName
          in: query
          description: cognome astronauta
          required: false
          type: string
          enum: ["Casati"]
      responses:
        200:
          description: lista degli astronauti (eventualmente selezionati per cognome)
          schema:
            $ref: '#/definitions/Astronauts'
    post:
      description: inserisce un astronauta
      operationId: sendAstronauts
      parameters:
        - name: dati_astronauta
          in: body
          description: tutti i dati dell'astronauta
          required: true
          schema: 
              $ref: '#/definitions/Astronauts_noID'
      responses:
        200:
          description: " "
          
  /{id}:  
    get:
      description: prendo un astronauta dato il suo id
      operationId: getAstronautsById
      parameters:
        - name: id
          in: path
          description: id astronauta
          required: true
          type: integer
      responses:
        200:
          description: astronauta
          schema:
            $ref: '#/definitions/Astronauts'
    put:
      description: aggiorno un astronauta dato il suo id
      operationId: updateAstronautsById
      parameters:
        - name: id
          in: path
          description: id astronauta
          required: true
          type: integer
      responses:
        200:
          description: "Astronaut 3 aggiornato"
        400:
          description: "Astronaut non trovato"

definitions:  

  Astronauts:   
    allOf:
      - $ref: '#/definitions/Astronauts_noID'
    required:
      - astronautsID
    properties:
      astronautsID:
        type: integer
        format: int32
        enum: ["42"]
      
  Astronauts_noID:      
    required:
      - firstName
      - lastName
      - isInSpace
    properties:
      firstName:
        type: string
        enum: ["Fabio"]
      lastName:
        type: string
        enum: ["Casati"]
      isInSpace:
        type: boolean
        enum: [false]